<?php

namespace AppBundle\Repository;

/**
 * FraudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraudRepository extends \Doctrine\ORM\EntityRepository
{
}
