<?php

namespace AppBundle\Repository;

/**
 * TwitterApiDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwitterApiDataRepository extends \Doctrine\ORM\EntityRepository
{
}
