<?php
/**
 * Created by PhpStorm.
 * User: anais
 * Date: 02/11/2018
 * Time: 13:36.
 */

namespace AppBundle\Service;

use Symfony\Component\HttpFoundation\File\Exception\FileException;

class UploadedFileService
{
    /**
     * @param mixed $file      the file to save
     * @param mixed $directory the file directory
     *
     * @return string
     */
    public function saveFile($file, $directory)
    {
        // $file stores the uploaded file
        /**
 * @var Symfony\Component\HttpFoundation\File\UploadedFile $file 
*/
        $fileName = $this->generateUniqueFileName().'.'.$file->getClientOriginalExtension();
        // Move the file to the directory where brochures are stored
        try {
            $file->move(
                $directory,
                $fileName
            );
        } catch (FileException $e) {
            // ... handle exception if something happens during file upload
        }

        return $fileName;
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
